import { describe, it, expect, beforeEach, vi } from 'vitest';
import { randomBytes } from 'node:crypto';
import { createDb, type Db } from '../../src/db/client';
import { createBinding } from '../../src/services/bindingService';
import { createGmailAccount } from '../../src/services/gmailAccountService';
import { recordThreadMessage, resolveThreadByDiscordMessageId } from '../../src/services/threadService';
import { sendNewEmail, sendReplyEmail } from '../../src/services/outboundEmailService';
import type { ResendClient } from '../../src/mail/resendClient';
import type { GmailClient } from '../../src/mail/gmailClient';

const GMAIL_KEY = randomBytes(32).toString('hex');

// Resend's send API returns its own email id — a bare UUID, deliberately NOT a Message-ID —
// so the fake mirrors that. The RFC-5322 Message-ID we thread on is generated by the service.
const RESEND_EMAIL_ID = '4ef9a417-02e9-4d39-ad75-9611e0fcc33c';
const MESSAGE_ID_PATTERN = /^<[0-9a-f-]{36}@octo\.jp>$/;

function fakeResend(overrides: Partial<ResendClient> = {}): ResendClient {
  return {
    sendEmail: vi.fn().mockResolvedValue({ id: RESEND_EMAIL_ID }),
    getReceivedEmail: vi.fn(),
    getAttachmentDownloadUrl: vi.fn(),
    verifyWebhookSignature: vi.fn(),
    ...overrides,
  };
}

describe('outboundEmailService', () => {
  let db: Db;

  beforeEach(async () => {
    db = createDb(':memory:');
    await createBinding(db, {
      emailAddress: 'tako@octo.jp',
      discordGuildId: 'guild-1',
      discordChannelId: 'chan-1',
      createdBy: 'user-1',
    });
  });

  describe('sendNewEmail', () => {
    it('sends via Resend and records an outbound thread row', async () => {
      const resend = fakeResend();
      const result = await sendNewEmail(db, { resend, gmail: null }, {
        discordChannelId: 'chan-1',
        discordMessageId: 'discord-msg-1',
        to: 'friend@example.com',
        subject: 'Hi',
        body: 'Hello there',
      });

      expect(result).toEqual({ ok: true, emailId: RESEND_EMAIL_ID });
      expect(resend.sendEmail).toHaveBeenCalledWith(expect.objectContaining({
        from: 'tako@octo.jp',
        to: 'friend@example.com',
        subject: 'Hi',
        text: 'Hello there',
      }));

      const thread = await resolveThreadByDiscordMessageId(db, 'discord-msg-1');
      expect(thread?.direction).toBe('outbound');
      expect(thread?.externalAddress).toBe('friend@example.com');
    });

    it('sends a generated RFC-5322 Message-ID and stores that (not the Resend id) for threading', async () => {
      const resend = fakeResend();
      await sendNewEmail(db, { resend, gmail: null }, {
        discordChannelId: 'chan-1',
        discordMessageId: 'discord-msg-mid',
        to: 'friend@example.com',
        subject: 'Hi',
        body: 'Hello there',
      });

      const sentHeaders = (resend.sendEmail as ReturnType<typeof vi.fn>).mock.calls[0][0].headers;
      expect(sentHeaders['Message-ID']).toMatch(MESSAGE_ID_PATTERN);

      const thread = await resolveThreadByDiscordMessageId(db, 'discord-msg-mid');
      expect(thread?.emailMessageId).toBe(sentHeaders['Message-ID']);
      expect(thread?.emailMessageId).not.toBe(RESEND_EMAIL_ID);
    });

    it('skips attachments over the Resend size budget and notes it in the body', async () => {
      const resend = fakeResend();
      // 21MB each: base64-encoded that is ~28MB, so the second one blows the 40MB budget.
      const big = () => Buffer.alloc(21 * 1024 * 1024);
      await sendNewEmail(db, { resend, gmail: null }, {
        discordChannelId: 'chan-1',
        discordMessageId: 'discord-msg-big',
        to: 'friend@example.com',
        subject: 'Hi',
        body: 'Hello',
        attachments: [
          { filename: 'first.bin', content: big() },
          { filename: 'second.bin', content: big() },
        ],
      });

      const sent = (resend.sendEmail as ReturnType<typeof vi.fn>).mock.calls[0][0];
      expect(sent.attachments.map((a: { filename: string }) => a.filename)).toEqual(['first.bin']);
      expect(sent.text).toBe('Hello\n\n(添付は容量超過のため省略されました)');
    });

    it('fails when the channel has no binding', async () => {
      const resend = fakeResend();
      const result = await sendNewEmail(db, { resend, gmail: null }, {
        discordChannelId: 'unbound-chan',
        discordMessageId: 'discord-msg-2',
        to: 'friend@example.com',
        subject: 'Hi',
        body: 'Hello',
      });
      expect(result.ok).toBe(false);
      expect(resend.sendEmail).not.toHaveBeenCalled();
    });

    it('returns an error result when Resend throws', async () => {
      const resend = fakeResend({ sendEmail: vi.fn().mockRejectedValue(new Error('rate limited')) });
      const result = await sendNewEmail(db, { resend, gmail: null }, {
        discordChannelId: 'chan-1',
        discordMessageId: 'discord-msg-3',
        to: 'friend@example.com',
        subject: 'Hi',
        body: 'Hello',
      });
      expect(result).toEqual({ ok: false, error: 'rate limited' });
    });

    it('still reports success when the send succeeds but recording the thread row fails', async () => {
      // The UNIQUE constraint on discord_message_id makes recordThreadMessage throw for a
      // duplicate id, simulating any bookkeeping failure that happens after a real send.
      const binding = await createBinding(db, { emailAddress: 'dup@octo.jp', discordGuildId: 'guild-1', discordChannelId: 'chan-dup', createdBy: 'u1' });
      await recordThreadMessage(db, {
        discordMessageId: 'already-used',
        bindingId: binding.id,
        externalAddress: 'someone@example.com',
        subject: 'Existing',
        emailMessageId: '<existing@octo.jp>',
        inReplyTo: null,
        referencesChain: null,
        direction: 'outbound',
      });

      const resend = fakeResend();
      const result = await sendNewEmail(db, { resend, gmail: null }, {
        discordChannelId: 'chan-dup',
        discordMessageId: 'already-used',
        to: 'friend@example.com',
        subject: 'Hi',
        body: 'Hello',
      });

      expect(result).toEqual({ ok: true, emailId: RESEND_EMAIL_ID });
      expect(resend.sendEmail).toHaveBeenCalled();
    });
  });

  describe('sendReplyEmail', () => {
    it('resolves the original thread, sets reply headers, and records a new row', async () => {
      const binding = await createBinding(db, {
        emailAddress: 'tai@octo.jp',
        discordGuildId: 'guild-1',
        discordChannelId: 'chan-2',
        createdBy: 'user-1',
      });
      await recordThreadMessage(db, {
        discordMessageId: 'inbound-msg-1',
        bindingId: binding.id,
        externalAddress: 'friend@example.com',
        subject: 'Original subject',
        emailMessageId: '<orig@x>',
        inReplyTo: null,
        referencesChain: null,
        direction: 'inbound',
      });

      const resend = fakeResend();
      const result = await sendReplyEmail(db, { resend, gmail: null }, {
        discordChannelId: 'chan-2',
        discordMessageId: 'discord-reply-1',
        repliedToDiscordMessageId: 'inbound-msg-1',
        body: 'Thanks!',
      });

      expect(result).toEqual({ ok: true, emailId: RESEND_EMAIL_ID });
      expect(resend.sendEmail).toHaveBeenCalledWith(expect.objectContaining({
        from: 'tai@octo.jp',
        to: 'friend@example.com',
        subject: 'Re: Original subject',
        text: 'Thanks!',
        headers: {
          'Message-ID': expect.stringMatching(MESSAGE_ID_PATTERN),
          'In-Reply-To': '<orig@x>',
          References: '<orig@x>',
        },
      }));

      const newThread = await resolveThreadByDiscordMessageId(db, 'discord-reply-1');
      expect(newThread?.referencesChain).toBe('<orig@x>');

      // The reply's own stored Message-ID must be the one we sent, so a further reply
      // to it threads on a real Message-ID rather than a bare Resend UUID.
      const sentHeaders = (resend.sendEmail as ReturnType<typeof vi.fn>).mock.calls[0][0].headers;
      expect(newThread?.emailMessageId).toBe(sentHeaders['Message-ID']);
    });

    it('fails when the replied-to message has no known thread', async () => {
      const resend = fakeResend();
      const result = await sendReplyEmail(db, { resend, gmail: null }, {
        discordChannelId: 'chan-1',
        discordMessageId: 'discord-reply-2',
        repliedToDiscordMessageId: 'unknown-msg',
        body: 'Thanks!',
      });
      expect(result.ok).toBe(false);
      expect(resend.sendEmail).not.toHaveBeenCalled();
    });

    it('returns an error result when Resend throws', async () => {
      const binding = await createBinding(db, {
        emailAddress: 'tai2@octo.jp',
        discordGuildId: 'guild-1',
        discordChannelId: 'chan-3',
        createdBy: 'user-1',
      });
      await recordThreadMessage(db, {
        discordMessageId: 'inbound-msg-2',
        bindingId: binding.id,
        externalAddress: 'friend@example.com',
        subject: 'Original subject',
        emailMessageId: '<orig2@x>',
        inReplyTo: null,
        referencesChain: null,
        direction: 'inbound',
      });

      const resend = fakeResend({ sendEmail: vi.fn().mockRejectedValue(new Error('rate limited')) });
      const result = await sendReplyEmail(db, { resend, gmail: null }, {
        discordChannelId: 'chan-3',
        discordMessageId: 'discord-reply-3',
        repliedToDiscordMessageId: 'inbound-msg-2',
        body: 'Thanks!',
      });
      expect(result).toEqual({ ok: false, error: 'rate limited' });
    });
  });

  describe('sendNewEmail with a Gmail-provider binding', () => {
    it('sends via GmailClient.sendRawMessage instead of Resend, and records the returned thread id', async () => {
      const binding = await createBinding(db, {
        emailAddress: 'tako@gmail.com',
        discordGuildId: 'guild-1',
        discordChannelId: 'chan-gmail',
        createdBy: 'user-1',
        provider: 'gmail',
      });
      await createGmailAccount(db, GMAIL_KEY, {
        bindingId: binding.id,
        refreshToken: 'refresh-1',
        accessToken: 'access-1',
        accessTokenExpiresAt: new Date(Date.now() + 3600_000),
        historyId: '1',
      });

      const resend = fakeResend();
      const gmailClient = {
        sendRawMessage: vi.fn().mockResolvedValue({ id: 'gmail-msg-1', threadId: 'gmail-thread-1' }),
      } as unknown as GmailClient;

      const result = await sendNewEmail(
        db,
        { resend, gmail: { client: gmailClient, tokenEncryptionKey: GMAIL_KEY } },
        {
          discordChannelId: 'chan-gmail',
          discordMessageId: 'discord-msg-gmail',
          to: 'friend@example.com',
          subject: 'Hi',
          body: 'Hello there',
        },
      );

      expect(result).toEqual({ ok: true, emailId: 'gmail-msg-1' });
      expect(resend.sendEmail).not.toHaveBeenCalled();
      expect(gmailClient.sendRawMessage).toHaveBeenCalledWith('access-1', expect.any(Buffer), undefined);

      const thread = await resolveThreadByDiscordMessageId(db, 'discord-msg-gmail');
      expect(thread?.gmailThreadId).toBe('gmail-thread-1');
    });

    it('fails with a clear error when Gmail is not configured for this deployment', async () => {
      await createBinding(db, {
        emailAddress: 'tako@gmail.com',
        discordGuildId: 'guild-1',
        discordChannelId: 'chan-gmail-2',
        createdBy: 'user-1',
        provider: 'gmail',
      });

      const result = await sendNewEmail(db, { resend: fakeResend(), gmail: null }, {
        discordChannelId: 'chan-gmail-2',
        discordMessageId: 'discord-msg-gmail-2',
        to: 'friend@example.com',
        subject: 'Hi',
        body: 'Hello',
      });

      expect(result).toEqual({ ok: false, error: 'Gmail連携が設定されていません。' });
    });
  });
});
